spring.application.name=wild-oasis
spring.datasource.url=jdbc:postgresql://localhost:5432/the_wild_oasis
spring.datasource.username=postgres
spring.datasource.password=password

supabase.url=${SUPABASE_URL}
supabase.service-key=${SUPABASE_SERVICE_KEY}
supabase.bucket=cabin-images
